## Упражнение № 1

Создайте Series из каждого из элементов: списка, ndarray и словаря.

Пример входных данных:

```python
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
```

In [1]:
import numpy as np
import pandas as pd

mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser1 = pd.Series(mylist)
ser2 = pd.Series(myarr)
ser3 = pd.Series(mydict)

## Упражнение № 2

Преобразуйте `ser` в датафрейм с его индексом в качестве еще одного столбца датафрейма.

Пример входных данных:

```python
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)
```

In [15]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)
df = ser.reset_index()
df.columns = ['index', 'value']
print(df)


   index  value
0      a      0
1      b      1
2      c      2
3      e      3
4      d      4
5      f      5
6      g      6
7      h      7
8      i      8
9      j      9
10     k     10
11     l     11
12     m     12
13     n     13
14     o     14
15     p     15
16     q     16
17     r     17
18     s     18
19     t     19
20     u     20
21     v     21
22     w     22
23     x     23
24     y     24
25     z     25


## Упражнение № 3

Объедините `ser1` и `ser2`, чтобы сформировать датафрейм.

Пример входных данных:

```python
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
```


In [16]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

ser1 = pd.Series(list(mydict.keys()))
ser2 = pd.Series(list(mydict.values()))

df = pd.DataFrame({'Column1': ser1, 'Column2': ser2})
print(df)


   Column1  Column2
0        a        0
1        b        1
2        c        2
3        e        3
4        d        4
5        f        5
6        g        6
7        h        7
8        i        8
9        j        9
10       k       10
11       l       11
12       m       12
13       n       13
14       o       14
15       p       15
16       q       16
17       r       17
18       s       18
19       t       19
20       u       20
21       v       21
22       w       22
23       x       23
24       y       24
25       z       25


## Упражнение № 4

Добавьте имя ряда  `ser`, назвав его `latin_letters`.

Пример входных данных:

```python
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
```

In [17]:
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser.name = 'latin_letters'
print(ser)


0     a
1     b
2     c
3     e
4     d
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
Name: latin_letters, dtype: object


## Упражнение № 5

Из `ser1` удалите элементы, присутствующие в `ser2`.

```python
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
```

In [18]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

result = ser1[~ser1.isin(ser2)]
print(result)


0    1
1    2
2    3
dtype: int64


## Упражнение № 6

Получить все элементы `ser1` и `ser2`, которые не являются общими для обоих рядов.

Пример входных данных:

```python
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])
```

In [19]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

result = pd.concat([ser1[~ser1.isin(ser2)], ser2[~ser2.isin(ser1)]])
print(result)


0    1
1    2
2    3
2    6
3    7
4    8
dtype: int64


## Упражнение № 7

Вычислите минимальное значение, 25-й процентиль, медиану, 75-й процентиль и максимальное значение `ser`.

Пример входных данных:

```python
ser = pd.Series(np.random.normal(10, 5, 25))
```

In [20]:
ser = pd.Series(np.random.normal(10, 5, 25))

statistics = {
    "min": ser.min(),
    "25%": ser.quantile(0.25),
    "median": ser.median(),
    "75%": ser.quantile(0.75),
    "max": ser.max(),
}

print(statistics)


{'min': np.float64(-5.241086891297826), '25%': np.float64(7.4557769523683985), 'median': np.float64(10.371139230888538), '75%': np.float64(14.139366084695457), 'max': np.float64(18.227593451218677)}


## Упражнение № 8

Вычислите частоту встречаемости каждого уникального значения `ser`.

Пример входных данных:

```python
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))
```

In [21]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

frequency = ser.value_counts()
print(frequency)


h    7
e    5
a    4
g    4
d    4
b    3
c    2
f    1
Name: count, dtype: int64


## Упражнение № 9

Из `ser` оставить 2 наиболее часто встречающихся элемента без изменений, а все остальные заменить на `Прочее`.

Пример входных данных:

```python
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))
```

In [26]:
np.random.RandomState(100)
ser = pd.Series(np.random.randint(1, 5, [12]))

top_two = ser.value_counts().index[:2]
ser[~ser.isin(top_two)] = 'Прочее'
print(ser)

0          4
1          2
2     Прочее
3     Прочее
4          4
5          4
6          4
7     Прочее
8     Прочее
9          2
10         2
11    Прочее
dtype: object


C:\Users\lewac\AppData\Local\Temp\ipykernel_18536\3962796178.py:5: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Прочее' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  ser[~ser.isin(top_two)] = 'Прочее'


## Упражнение № 10

Разбейте ряд `ser` на 10 равных децилей и замените значения на название дециля.

Пример входных данных:

```python
ser = pd.Series(np.random.random(20))
```

Пример выходных данных:

```python
# First 5 items
0    7th
1    9th
2    7th
3    3rd
4    8th
dtype: category
Categories (10, object): [1st < 2nd < 3rd < 4th ... 7th < 8th < 9th < 10th]
```


In [27]:
ser = pd.Series(np.random.random(20))

labels = ['{}th'.format(i) for i in range(1, 11)]
ser_bins = pd.qcut(ser, 10, labels=labels)

print(ser_bins)


0      3th
1      5th
2      3th
3      1th
4      2th
5      8th
6      4th
7     10th
8      4th
9      6th
10     2th
11    10th
12     7th
13     1th
14     6th
15     7th
16     9th
17     8th
18     5th
19     9th
dtype: category
Categories (10, object): ['1th' < '2th' < '3th' < '4th' ... '7th' < '8th' < '9th' < '10th']


## Упражнение № 11

Переформируйте ряд `ser` в датафрейм с 7 строками и 5 столбцами

Пример входных данных:

```python
ser = pd.Series(np.random.randint(1, 10, 35))
```

In [28]:
ser = pd.Series(np.random.randint(1, 10, 35))
df = ser.values.reshape(7, 5)
print(pd.DataFrame(df))


   0  1  2  3  4
0  4  3  5  7  3
1  8  4  8  5  9
2  5  2  5  3  7
3  8  1  3  2  7
4  2  4  5  7  7
5  3  2  6  1  2
6  1  9  4  5  1


## Упражнение № 12

Найти позиции чисел, кратных 3, из ряда `ser`.

Пример входных данных:

```python
ser = pd.Series(np.random.randint(1, 10, 7))
```

In [31]:
ser = pd.Series(np.random.randint(1, 10, 7))
positions = ser[ser % 3 == 0].index.tolist()
print(positions)


[2, 3, 5]


## Упражнение № 13

Из `ser` извлечь элементы, находящиеся на позициях в списке `pos`.

Пример входных данных:

```python
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]
```


In [32]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

result = ser.iloc[pos]
print(result)


0     a
4     e
8     i
14    o
20    u
dtype: object


## Упражнение № 14

Объедините `ser1` и `ser2` по вертикали и горизонтали (чтобы сформировать датафрейм).

Пример входных данных:

```python
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))
```

In [33]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

df_horizontal = pd.concat([ser1, ser2], axis=1)
df_vertical = pd.concat([ser1, ser2], axis=0)

print("Horizontal:")
print(df_horizontal)
print("Vertical:")
print(df_vertical)

Horizontal:
   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e
Vertical:
0    0
1    1
2    2
3    3
4    4
0    a
1    b
2    c
3    d
4    e
dtype: object


## Упражнение № 15

Получите позиции элементов `ser2` в `ser1` в виде списка.

Пример входных данных:

```python
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])
```

In [34]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

positions = [ser1[ser1 == value].index[0] for value in ser2]
print(positions)


[np.int64(5), np.int64(4), np.int64(0), np.int64(8)]


## Упражнение № 16

Вычислить среднеквадратическую ошибку рядов `truth` и `pred`.

Пример входных данных:

```python
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)
```

In [35]:
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

mse = ((truth - pred) ** 2).mean()
print(mse)

0.4322869950466016


## Упражнение № 17

В каждом слове `ser` поставьте первый символ каждого слова в верхний регистр.

```python
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
```

In [36]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
capitalized = ser.str.capitalize()
print(capitalized)


0     How
1      To
2    Kick
3    Ass?
dtype: object


## Упражнение № 18

В каждом слове `ser` посчитайте число символов.

Пример входных данных:

```python
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
```

In [37]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])
lengths = ser.str.len()
print(lengths)

0    3
1    2
2    4
3    4
dtype: int64


## Упражнение № 19

Вычислите разность разностей между последовательно идущими числами в `ser`.

Пример входных данных:

```python
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])
```

Пример выходных данных:

```
[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]
```


In [38]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

first_diff = ser.diff()
second_diff = first_diff.diff()

print(first_diff)
print(second_diff)

0    NaN
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
6    6.0
7    8.0
dtype: float64
0    NaN
1    NaN
2    1.0
3    1.0
4    1.0
5    1.0
6    0.0
7    2.0
dtype: float64


## Упражнение № 20

Преобразуйте строковое представление дат в `datetime64`.

Пример входных данных:

```python
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
```

Пример выходных данных:

```
0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]
```

In [42]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

formats = ['%d %b %Y', '%d-%m-%Y', '%Y%m%d', '%Y/%m/%d', '%Y-%m-%d', '%Y-%m-%dT%H:%M']

datetime_ser = ser.apply(
    lambda x: pd.to_datetime(x, errors='coerce', format=None)
)
print(datetime_ser)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]


## Упражнение № 21

Получите из `ser` день месяца, номер недели, день года и день недели.

Пример входных данных:

```python
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])
```

Пример выходных данных:

```
Date:  [1, 2, 3, 4, 5, 6]
Week number:  [53, 5, 9, 14, 19, 23]
Day num of year:  [1, 33, 63, 94, 125, 157]
Day of week:  ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']
```

In [49]:
ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

dates = pd.to_datetime(ser, format='mixed')
day_of_month = dates.dt.day
week_number = dates.dt.isocalendar().week
day_of_year = dates.dt.dayofyear
day_of_week = dates.dt.day_name()

print("Date:", day_of_month.tolist())
print("Week number:", week_number.tolist())
print("Day num of year:", day_of_year.tolist())
print("Day of week:", day_of_week.tolist())

Date: [1, 2, 3, 4, 5, 6]
Week number: [53, 5, 9, 14, 19, 23]
Day num of year: [1, 33, 63, 94, 125, 157]
Day of week: ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']


## Упражнение № 22

Замените элементы `ser` на даты, начинающиеся с 4-го числа соответствующего месяца.

Пример входных данных:

```python
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])
```

Пример выходных данных:

```
0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]
```

In [4]:
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])
ser = pd.to_datetime(ser) + pd.offsets.Day(3)
print(ser)

0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]


C:\Users\lewac\AppData\Local\Temp\ipykernel_3140\840979140.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  ser = pd.to_datetime(ser) + pd.offsets.Day(3)


## Упражнение № 23

Из `ser` извлеките слова, содержащие не менее 2 гласных букв.

Пример входных данных:

```python
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])
```

Пример выходных данных:

```
0     Apple
1    Orange
4     Money
dtype: object
```


In [6]:
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])
vowels = "aeiouAEIOU"
filtered = ser[ser.str.count(f"[{vowels}]") >= 2]
print(filtered)

0     Apple
1    Orange
4     Money
dtype: object


## Упражнение № 24

Извлеките корректные адреса электронной почты из ряда `emails`. Шаблон регулярного выражения для корректных адресов электронной почты приведен в качестве образца.

Пример входных данных:

```python
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
```

Пример выходных данных:

```
1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object
```

In [7]:
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])
pattern = '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}'
valid_emails = emails[emails.str.contains(pattern, regex=True)]
print(valid_emails)

1    rameses@egypt.com
2            matt@t.co
3    narendra@modi.com
dtype: object


<>:2: SyntaxWarning: invalid escape sequence '\.'
<>:2: SyntaxWarning: invalid escape sequence '\.'
C:\Users\lewac\AppData\Local\Temp\ipykernel_3140\1539219037.py:2: SyntaxWarning: invalid escape sequence '\.'
  pattern = '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}'


## Упражнение № 25

Вычислить среднее значение веса в `weights` для каждого фрукта из `fruit`.

Пример входных данных:

```python
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
print(weight.tolist())
print(fruit.tolist())
#> [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0]
#> ['banana', 'carrot', 'apple', 'carrot', 'carrot', 'apple', 'banana', 'carrot', 'apple', 'carrot']
```

Пример выходных данных:

```python
# values can change due to randomness
apple     6.0
banana    4.0
carrot    5.8
dtype: float64
```

In [9]:
import numpy as np

fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))
mean_weights = weights.groupby(fruit).mean()
print(mean_weights)


apple     2.000000
banana    8.000000
carrot    3.666667
dtype: float64


## Упражнение № 26

Вычислить [евклидово расстояние](https://en.wikipedia.org/wiki/Euclidean_distance) между векторами $p$ и $q$, не используя встроенную формулу.

Пример входных данных:

```python
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
```

Пример выходных данных:

```
18.165
```

In [11]:
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
distance = np.sqrt(((p - q) ** 2).sum())
print(distance)

18.16590212458495


## Упражнение № 27

Получите позиции пиков (значений, окруженных с двух сторон меньшими значениями) в `ser`.

Пример входных данных:

```python
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])
```

Пример выходных данных:

```
array([1, 5, 7])
```

In [12]:
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])
peaks = np.where((ser > ser.shift(1)) & (ser > ser.shift(-1)))[0]
print(peaks)


[1 5 7]


## Упражнение № 28

Замените пробелы в `my_str` на наименее часто встречающийся символ.

Пример входных данных:

```python
my_str = 'dbc deb abed gade'
```

Пример выходных данных:

```
'dbccdebcabedcgade'  # least frequent is 'c'
```

In [13]:
from collections import Counter

my_str = 'dbc deb abed gade'
freq = Counter(my_str.replace(' ', ''))
char = freq.most_common()[-1][0]
result = my_str.replace(' ', char)
print(result)

dbcgdebgabedggade


## Упражнение № 29

Создайте временной ряд, начинающийся с `2000-01-01`, содержащий 10 субботних дней после этого и имеющий в качестве значений случайные числа

Пример выходных данных:

```
# values can be random
2000-01-01    4
2000-01-08    1
2000-01-15    8
2000-01-22    4
2000-01-29    4
2000-02-05    2
2000-02-12    4
2000-02-19    9
2000-02-26    6
2000-03-04    6
```

In [14]:
dates = pd.date_range(start='2000-01-01', periods=10, freq='7D')
random_values = np.random.randint(1, 10, size=10)
time_series = pd.Series(random_values, index=dates)
print(time_series)

2000-01-01    2
2000-01-08    1
2000-01-15    7
2000-01-22    5
2000-01-29    6
2000-02-05    5
2000-02-12    7
2000-02-19    7
2000-02-26    3
2000-03-04    3
Freq: 7D, dtype: int32


## Упражнение № 30

В `ser` отсутствуют некоторые даты и значения. Сделайте так, чтобы все отсутствующие даты появились и заполнились значением из предыдущей даты.

Пример входных данных:

```python
ser = pd.Series([1,10,3,np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
print(ser)
#> 2000-01-01     1.0
#> 2000-01-03    10.0
#> 2000-01-06     3.0
#> 2000-01-08     NaN
#> dtype: float64
```

Пример выходных данных:

```
2000-01-01     1.0
2000-01-02     1.0
2000-01-03    10.0
2000-01-04    10.0
2000-01-05    10.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     NaN
```

In [25]:
ser = pd.Series([1, 10, 3, np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))
ser = ser.reindex(pd.date_range(start=ser.index.min(), end=ser.index.max(), freq='D')).fillna(method='ffill')
print(ser)

2000-01-01    1.0000
2000-01-02    1.0000
2000-01-03   10.0000
2000-01-04   10.0000
2000-01-05   10.0000
2000-01-06    3.0000
2000-01-07    3.0000
2000-01-08    3.0000
Freq: D, dtype: float64


C:\Users\lewac\AppData\Local\Temp\ipykernel_5812\4215555315.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  ser = ser.reindex(pd.date_range(start=ser.index.min(), end=ser.index.max(), freq='D')).fillna(method='ffill')


## Упражнение № 31

Вычислите автокорреляции для первых 10 лагов `ser`. Определите, какой из лагов имеет наибольшую корреляцию. (см. также [Модель авторегрессии и распределённого лага — Википедия](https://ru.wikipedia.org/wiki/%D0%9C%D0%BE%D0%B4%D0%B5%D0%BB%D1%8C_%D0%B0%D0%B2%D1%82%D0%BE%D1%80%D0%B5%D0%B3%D1%80%D0%B5%D1%81%D1%81%D0%B8%D0%B8_%D0%B8_%D1%80%D0%B0%D1%81%D0%BF%D1%80%D0%B5%D0%B4%D0%B5%D0%BB%D1%91%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE_%D0%BB%D0%B0%D0%B3%D0%B0))

Пример входных данных:

```python
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))
```

Пример выходных данных:

```
# values will change due to randomness
[0.29999999999999999, -0.11, -0.17000000000000001, 0.46000000000000002, 0.28000000000000003, -0.040000000000000001, -0.37, 0.41999999999999998, 0.47999999999999998, 0.17999999999999999]
Lag having highest correlation:  9
```

In [19]:
ac = [ser.autocorr(lag) for lag in range(1, 11)]
max_lag = np.argmax(ac) + 1
print(ac)
print("Lag having highest correlation:", max_lag)

[np.float64(0.3936465655286895), np.float64(-0.4344738780433504), np.float64(-1.0), np.float64(-0.5773502691896257), np.float64(nan), np.float64(nan), np.float64(nan), nan, nan, nan]
Lag having highest correlation: 5


## Упражнение № 32

Импортируйте каждую 50-ю строку набора данных [BostonHousing dataset](https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv) в виде датафрейма.

In [20]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', skiprows=lambda x: x % 50 != 0)
print(df)

      crim  zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.21977   0   6.91     0  0.448  5.602  62.0  6.0877    3  233     17.9   
1  0.06860   0   2.89     0  0.445  7.416  62.5  3.4952    2  276     18.0   
2  2.73397   0  19.58     0  0.871  5.597  94.9  1.5257    5  403     14.7   
3  0.03150  95   1.47     0  0.403  6.975  15.3  7.6534    3  402     17.0   
4  0.19073  22   5.86     0  0.431  6.718  17.5  7.8265    7  330     19.1   
5  0.05561  70   2.24     0  0.400  7.041  10.0  7.8278    5  358     14.8   
6  0.02899  40   1.25     0  0.429  6.939  34.5  8.7921    1  335     19.7   
7  9.91655   0  18.10     0  0.693  5.852  77.8  1.5004   24  666     20.2   
8  7.52601   0  18.10     0  0.713  6.417  98.3  2.1850   24  666     20.2   
9  0.17783   0   9.69     0  0.585  5.569  73.5  2.3999    6  391     19.2   

        b  lstat  medv  
0  396.90  16.20  19.4  
1  396.90   6.19  33.2  
2  351.85  21.45  15.4  
3  396.90   4.56  34.9  
4  393.74   6.56

## Упражнение № 33

Импортируйте набор данных [boston housing dataset](https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv), но при импорте измените столбец `'medv'` (*median house value*) так, чтобы значения < 25 стали `Low`, а > 25 - `High`.


In [21]:
df['medv'] = df['medv'].apply(lambda x: 'Low' if x < 25 else 'High')
print(df.head())

      crim  zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.21977   0   6.91     0  0.448  5.602  62.0  6.0877    3  233     17.9   
1  0.06860   0   2.89     0  0.445  7.416  62.5  3.4952    2  276     18.0   
2  2.73397   0  19.58     0  0.871  5.597  94.9  1.5257    5  403     14.7   
3  0.03150  95   1.47     0  0.403  6.975  15.3  7.6534    3  402     17.0   
4  0.19073  22   5.86     0  0.431  6.718  17.5  7.8265    7  330     19.1   

        b  lstat  medv  
0  396.90  16.20   Low  
1  396.90   6.19  High  
2  351.85  21.45   Low  
3  396.90   4.56  High  
4  393.74   6.56  High  


## Упражнение № 34

Создайте датафрейм со строками в виде шагов (интервалов) заданного ряда

Пример входных данных:

```python
L = pd.Series(range(15))
```

Пример выходных данных:

```
array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]])
```


In [35]:
L = pd.Series(range(15))

n = 4
result = np.array([L[i:i + n].values for i in range(len(L) - n + 1)])

print(result)

[[ 0  1  2  3]
 [ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


## Упражнение № 35

Импортируйте столбцы 'crim' и 'medv' из набора данных [BostonHousing dataset](https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv) в виде датафрейма.

In [24]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', usecols=['crim', 'medv'])
print(df)

        crim  medv
0    0.00632  24.0
1    0.02731  21.6
2    0.02729  34.7
3    0.03237  33.4
4    0.06905  36.2
..       ...   ...
501  0.06263  22.4
502  0.04527  20.6
503  0.06076  23.9
504  0.10959  22.0
505  0.04741  11.9

[506 rows x 2 columns]


## Упражнение № 36

Получите количество строк, столбцов, тип данных и суммарную статистику каждого столбца набора данных [Cars93](https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv). Также получите эквивалент датафрейма в виде numpy-массива и списка.


In [25]:
print("Количество строк и столбцов:", df.shape)
print("Типы данных:", df.dtypes)
print("Суммарная статистика:", df.describe())
print("Numpy массив:", df.to_numpy())
print("Список:", df.values.tolist())

Количество строк и столбцов: (506, 2)
Типы данных: crim    float64
medv    float64
dtype: object
Суммарная статистика:              crim        medv
count  506.000000  506.000000
mean     3.613524   22.532806
std      8.601545    9.197104
min      0.006320    5.000000
25%      0.082045   17.025000
50%      0.256510   21.200000
75%      3.677083   25.000000
max     88.976200   50.000000
Numpy массив: [[6.3200e-03 2.4000e+01]
 [2.7310e-02 2.1600e+01]
 [2.7290e-02 3.4700e+01]
 ...
 [6.0760e-02 2.3900e+01]
 [1.0959e-01 2.2000e+01]
 [4.7410e-02 1.1900e+01]]
Список: [[0.00632, 24.0], [0.02731, 21.6], [0.02729, 34.7], [0.03237, 33.4], [0.06905, 36.2], [0.02985, 28.7], [0.08829, 22.9], [0.14455, 27.1], [0.21124, 16.5], [0.17004, 18.9], [0.22489, 15.0], [0.11747, 18.9], [0.09378, 21.7], [0.62976, 20.4], [0.63796, 18.2], [0.62739, 19.9], [1.05393, 23.1], [0.7842, 17.5], [0.80271, 20.2], [0.7258, 18.2], [1.25179, 13.6], [0.85204, 19.6], [1.23247, 15.2], [0.98843, 14.5], [0.75026, 15.6], [0.84054,

## Упражнение № 37

Извлеките номер строки и столбца конкретной ячейки по заданному критерию.

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [36]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

max_price_idx = df['Price'].idxmax()
manufacturer, model, car_type = df.loc[max_price_idx, ['Manufacturer', 'Model', 'Type']]
print(f"Производитель: {manufacturer}, Модель: {model}, Тип: {car_type}")

row_number = max_price_idx
col_number = df.columns.get_loc('Price')
print(f"Номер строки: {row_number}, Номер столбца: {col_number}")

Производитель: Mercedes-Benz, Модель: 300E, Тип: Midsize
Номер строки: 58, Номер столбца: 4


## Упражнение № 38

Переименуйте в `df` столбец `Type` в `CarType` и замените `.` в именах столбцов на `_`.

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.columns)
#> Index(['Manufacturer', 'Model', 'Type', 'Min.Price', 'Price', 'Max.Price',
#>        'MPG.city', 'MPG.highway', 'AirBags', 'DriveTrain', 'Cylinders',
#>        'EngineSize', 'Horsepower', 'RPM', 'Rev.per.mile', 'Man.trans.avail',
#>        'Fuel.tank.capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
#>        'Turn.circle', 'Rear.seat.room', 'Luggage.room', 'Weight', 'Origin',
#>        'Make'],
#>       dtype='object')
```

Пример выходных данных:

```python
print(df.columns)
#> Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
#>        'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
#>        'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
#>        'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
#>        'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
#>        'Make'],
#>       dtype='object')
```

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df.rename(columns={'Type': 'CarType'}, inplace=True)
df.columns = df.columns.str.replace('.', '_')
print(df.columns)

Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
       'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
       'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


## Упражнение № 39

Проверьте, нет ли в `df` отсутствующих значений.

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [5]:
missing = df.isnull().any().any()
print("Пропущенные значения:", missing)

Пропущенные значения: True


## Упражнение № 40

Подсчитайте количество пропущенных значений в каждом столбце `df`. Какой столбец имеет наибольшее число пропущенных значений?

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [6]:
missing_counts = df.isnull().sum()
max_missing_col = missing_counts.idxmax()
print("Пропущенные значения по столбцам:\n", missing_counts)
print("Столбец с наибольшим количеством пропущенных значений:", max_missing_col)

Пропущенные значения по столбцам:
 Manufacturer           4
Model                  1
CarType                3
Min_Price              7
Price                  2
Max_Price              5
MPG_city               9
MPG_highway            2
AirBags               38
DriveTrain             7
Cylinders              5
EngineSize             2
Horsepower             7
RPM                    3
Rev_per_mile           6
Man_trans_avail        5
Fuel_tank_capacity     8
Passengers             2
Length                 4
Wheelbase              1
Width                  6
Turn_circle            5
Rear_seat_room         4
Luggage_room          19
Weight                 7
Origin                 5
Make                   3
dtype: int64
Столбец с наибольшим количеством пропущенных значений: AirBags


## Упражнение № 41

Замените отсутствующие значения в столбцах `Min.Price` и `Max.Price` на соответствующие им средние значения.

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [7]:
df =pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv',usecols=['Max.Price','Min.Price'])

df['Min.Price'] = df['Min.Price'].fillna(df['Min.Price'].mean())
df['Max.Price'] = df['Max.Price'].fillna(df["Max.Price"].mean())
df

Min.Price  Max.Price
0   12.900000  18.800000
1   29.200000  38.700000
2   25.900000  32.300000
3   17.118605  44.600000
4   17.118605  21.459091
..        ...        ...
88  16.600000  22.700000
89  17.600000  22.400000
90  22.900000  23.700000
91  21.800000  23.500000
92  24.800000  28.500000

[93 rows x 2 columns]

## Упражнение № 42

В `df` с помощью метода `apply` замените недостающие значения в `Min.Price` на среднее значение столбца, а в `Max.Price` — на медиану столбца.

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [8]:
df =pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv',usecols=['Max.Price','Min.Price'])

df['Min.Price'] = df['Min.Price'].apply(lambda x: df['Min.Price'].mean() if pd.isna(x) else x)
df['Max.Price'] = df["Max.Price"].apply(lambda x: df['Max.Price'].median() if pd.isna(x) else x)

df

Min.Price  Max.Price
0   12.900000      18.80
1   29.200000      38.70
2   25.900000      32.30
3   17.118605      44.60
4   17.118605      19.15
..        ...        ...
88  16.600000      22.70
89  17.600000      22.40
90  22.900000      23.70
91  21.800000      23.50
92  24.800000      28.50

[93 rows x 2 columns]

## Упражнение № 43

Получите первый столбец (`a`) в `df` в виде датафрейма (а не в виде ряда).

Пример входных данных:

```python
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
```

In [13]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
first_column_df = df[['a']]
print(first_column_df)
print("\n" + "="*80 + "\n")

    a
0   0
1   5
2  10
3  15




## Упражнение № 44

1. В `df` поменяйте местами столбцы `'a'` и `'c'`.
2. Создайте обобщенную функцию для обмена данными между двумя столбцами без фиксированного задания имен столбцов.
3. Отсортируйте столбцы в обратном алфавитном порядке, т.е. от столбца `'e'` до столбца `'a'`.

Пример входных данных:

```python
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))
```

In [14]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

cols = list(df.columns)
a, c = cols.index('a'), cols.index('c')
cols[a], cols[c] = cols[c], cols[a]
print(df[cols],'\n')

def swap_columnns(df: pd.DataFrame, col1, col2):
    cols = list(df.columns)
    a, b = cols.index(col1), cols.index(col2)
    cols[a], cols[b] = cols[b], cols[a]
    return df[cols]

print(swap_columnns(df,'a','c'))

df.sort_index(axis=1,ascending=False)

    c   b   a   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19 

    c   b   a   d   e
0   2   1   0   3   4
1   7   6   5   8   9
2  12  11  10  13  14
3  17  16  15  18  19


e   d   c   b   a
0   4   3   2   1   0
1   9   8   7   6   5
2  14  13  12  11  10
3  19  18  17  16  15

## Упражнение № 45

Измените настройки отображения `pandas` при выводе на печать датафрейма `df`, чтобы он показывал максимум 10 строк и 10 столбцов.

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [17]:
df =pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 10)
df 

Manufacturer    Model     Type  Min.Price  Price  ...  Rear.seat.room  \
0         Acura  Integra    Small       12.9   15.9  ...            26.5   
1           NaN   Legend  Midsize       29.2   33.9  ...            30.0   
2          Audi       90  Compact       25.9   29.1  ...            28.0   
3          Audi      100  Midsize        NaN   37.7  ...            31.0   
4           BMW     535i  Midsize        NaN   30.0  ...            27.0   
..          ...      ...      ...        ...    ...  ...             ...   
88   Volkswagen  Eurovan      Van       16.6   19.7  ...            34.0   
89   Volkswagen   Passat  Compact       17.6   20.0  ...            31.5   
90   Volkswagen  Corrado   Sporty       22.9   23.3  ...            26.0   
91        Volvo      240  Compact       21.8   22.7  ...            29.5   
92          NaN      850  Midsize       24.8   26.7  ...            30.0   

    Luggage.room  Weight   Origin                Make  
0            NaN  2705.0  non-USA       Acura Integra  
1           15.0  3560.0  non-USA        Acura Legend  
2           14.0  3375.0  non-USA             Audi 90  
3           17.0  3405.0  non-USA            Audi 100  
4           13.0  3640.0  non-USA            BMW 535i  
..           ...     ...      ...                 ...  
88           NaN  3960.0      NaN  Volkswagen Eurovan  
89          14.0  2985.0  non-USA   Volkswagen Passat  
90          15.0  2810.0  non-USA  Volkswagen Corrado  
91          14.0  2985.0  non-USA           Volvo 240  
92          15.0  3245.0  non-USA           Volvo 850  

[93 rows x 27 columns]

## Упражнение № 46

Исключите вывод научной нотации типа 'e-03' в `df` и выведите до 4 чисел после запятой.

Пример входных данных:

```python
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])
df
#>          random
#> 0  3.474280e-03
#> 1  3.951517e-05
#> 2  7.469702e-02
#> 3  5.541282e-28
```

Пример выходных данных:

```python
#>    random
#> 0  0.0035
#> 1  0.0000
#> 2  0.0747
#> 3  0.0000
```

In [21]:
df = pd.DataFrame(np.random.random(4)**10, columns=['random'])
round(df,4)

random
0  0.0000
1  0.8517
2  0.0000
3  0.0000

## Упражнение № 47

Отформатируйте значения в столбце `'random'` из `df` в виде процентов.

Пример входных данных:

```python
df = pd.DataFrame(np.random.random(4), columns=['random'])
df
#>      random
#> 0    .689723
#> 1    .957224
#> 2    .159157
#> 3    .21082
```

Пример выходных данных:

```python
#>      random
#> 0    68.97%
#> 1    95.72%
#> 2    15.91%
#> 3    2.10%
```

In [22]:
df = pd.DataFrame(np.random.random(4), columns=['random'])

df = (df['random']*100).round(2).astype(str) + '%'
df.to_frame()

random
0   26.0%
1  82.05%
2   9.07%
3  85.49%

## Упражнение № 48

Из `df` отфильтруйте значения `Manufacturer`, `Model` и `Type` для каждой 20-й строки, начиная с 1-й (строка 0).

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [23]:
df=pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv',usecols=['Manufacturer','Model','Type'])

df.filter(items=[i for i in range(0,df.__len__(),20)],axis=0)

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

## Упражнение № 49

В `df` замените `NaN` на `missing` в столбцах `Manufacturer`, `Model` и `Type` , создайте индекс как комбинацию этих трех столбцов и проверьте, является ли этот индекс первичным ключом.

Пример входных данных:

```python
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])
```

Пример выходных данных:

```
                       Manufacturer    Model     Type  Min.Price  Max.Price
Acura_Integra_Small           Acura  Integra    Small       12.9       18.8
missing_Legend_Midsize      missing   Legend  Midsize       29.2       38.7
Audi_90_Compact                Audi       90  Compact       25.9       32.3
Audi_100_Midsize               Audi      100  Midsize        NaN       44.6
BMW_535i_Midsize                BMW     535i  Midsize        NaN        NaN
```

In [26]:
df =pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

df[['Manufacturer','Model','Type']] = df[['Manufacturer','Model','Type']].fillna('missing')
df

Manufacturer    Model     Type  Min.Price  Max.Price
0         Acura  Integra    Small    12.9000    18.8000
1       missing   Legend  Midsize    29.2000    38.7000
2          Audi       90  Compact    25.9000    32.3000
3          Audi      100  Midsize        NaN    44.6000
4           BMW     535i  Midsize        NaN        NaN
..          ...      ...      ...        ...        ...
88   Volkswagen  Eurovan      Van    16.6000    22.7000
89   Volkswagen   Passat  Compact    17.6000    22.4000
90   Volkswagen  Corrado   Sporty    22.9000    23.7000
91        Volvo      240  Compact    21.8000    23.5000
92      missing      850  Midsize    24.8000    28.5000

[93 rows x 5 columns]

## Упражнение № 50

Найти положение строки с 5-м наибольшим значением столбца `'a'` в `df`.

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10,-1), columns=list('abc'))
```

In [27]:
df = pd.DataFrame(np.random.randint(1, 30, 30).reshape(10, -1), columns=list('abc'))
print(df)
print(f"Строка с 5-м наибольшим значением в столбце 'a': {df['a'].nlargest(5).index[-1]}")

    a   b   c
0  16  17  11
1  23  22  13
2  12  20   7
3  15   1  13
4  25  24   8
5  12  19   4
6  11  21  18
7  11  21  19
8  29  18  11
9  22   1   8
Строка с 5-м наибольшим значением в столбце 'a': 0


## Упражнение № 51

В `ser` найдите положение 2-го наибольшего значения, превышающего среднее.

Пример входных данных:

```python
ser = pd.Series(np.random.randint(1, 100, 15))
```

In [28]:
ser = pd.Series(np.random.randint(1, 100, 15))
mean_value = ser.mean()
second_largest = ser[ser > mean_value].nlargest(2).index[-1]
print(second_largest)

5


## Упражнение № 52

Получите две последние строки `df`, сумма строк которых больше 100.

```python
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
```

In [29]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
df[df.sum(axis=1) > 100].tail(2)

0   1   2   3
7   36  36  28  36
12  27  20  37  28

## Упражнение № 53

Замените все значения `ser`, находящиеся ниже 5%-ного и выше 95%-ного перцентиля, на соответствующие значения 5-го и 95-го перцентиля.

Пример входных данных:

```python
ser = pd.Series(np.logspace(-2, 2, 30))
```

In [30]:
ser = pd.Series(np.logspace(-2, 2, 30))

percentile_5 = np.percentile(ser, 5)
percentile_95 = np.percentile(ser, 95)
ser = ser.apply(lambda x: percentile_5 if x < percentile_5 else (percentile_95 if x > percentile_95 else x))

print(ser)

0     0.0160
1     0.0160
2     0.0189
3     0.0259
4     0.0356
       ...  
25   28.0722
26   38.5662
27   52.9832
28   63.8767
29   63.8767
Length: 30, dtype: float64


## Упражнение № 54

Перестройте `df` в максимально возможный квадрат с удалением отрицательных значений. При необходимости отбросьте наименьшие значения. Порядок положительных чисел в результате должен остаться тем же, что и в исходном варианте.

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))
```

In [31]:
df = pd.DataFrame(np.random.randint(-20, 50, 100).reshape(10,-1))
positive = df[df > 0].values.flatten()
n = int(np.sqrt(positive.__len__()))
pd.DataFrame(positive[:n*n].reshape(n, n))

0       1       2       3       4       5       6       7       8  \
0     NaN     NaN 20.0000 43.0000 36.0000 38.0000     NaN 19.0000 16.0000   
1  5.0000     NaN  7.0000     NaN 47.0000     NaN     NaN     NaN     NaN   
2     NaN  3.0000 15.0000 26.0000 37.0000 49.0000 32.0000  5.0000     NaN   
3     NaN     NaN 16.0000 11.0000 28.0000 38.0000     NaN     NaN 13.0000   
4 17.0000  2.0000     NaN 16.0000 46.0000  6.0000 45.0000  3.0000 26.0000   
5 12.0000 33.0000 47.0000     NaN  3.0000 38.0000     NaN     NaN     NaN   
6 42.0000     NaN 20.0000 35.0000  5.0000     NaN 24.0000 16.0000 38.0000   
7 27.0000 45.0000  6.0000  6.0000  2.0000 40.0000 27.0000 21.0000 46.0000   
8 36.0000 46.0000 38.0000  3.0000 13.0000 12.0000  6.0000 38.0000 32.0000   
9 47.0000 46.0000 17.0000 43.0000 26.0000     NaN 27.0000 43.0000  8.0000   

        9  
0  1.0000  
1 29.0000  
2     NaN  
3 20.0000  
4 20.0000  
5     NaN  
6     NaN  
7 21.0000  
8 39.0000  
9 22.0000

## Упражнение № 55

Поменяйте местами строки 1 и 2 в `df`.

Пример входных данных:

```python
df = pd.DataFrame(np.arange(25).reshape(5, -1))
```

In [32]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))
df[:2] = df[:2][::-1]
df

0   1   2   3   4
0   5   6   7   8   9
1   0   1   2   3   4
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

## Упражнение № 56

Переверните строки датафрейма `df` (первая строка становится последней).

Пример входных данных:

```python
df = pd.DataFrame(np.arange(25).reshape(5, -1))
```


In [33]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))
df = df.iloc[::-1]
print(df)

    0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4


## Упражнение № 57

Получите бинарный код для столбца `'a'` в датафрейме `df` и добавьте его в виде столбцов.

Пример входных данных:

```python
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))
    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24
```

Пример выходных данных:

```python
   0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24
```


In [34]:
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))

binary_columns = pd.get_dummies(df['a'])
binary_columns = binary_columns.astype(int)

df = pd.concat([binary_columns, df[['b', 'c', 'd', 'e']]], axis=1)
print(df)

   0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24


## Упражнение № 58

Получите название столбца с наибольшим количеством строчных максимумов в `df`.

```python
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))
```

In [35]:
df = pd.DataFrame(np.random.randint(1, 100, 40).reshape(10, -1))

max_column = df.idxmax(axis=1).value_counts().idxmax()
print(df)
print("\nНазвание столбца:", max_column)

    0   1   2   3
0   1  60  23  96
1  84  18  55  24
2  44  28  40  33
3   2  31  42  83
4   5  74  68  69
5  45  80  50  61
6   1   4  70  90
7   4  31  62  55
8  76  23  98  77
9  68  65  89  61

Название столбца: 3


## Упражнение № 59

Создать новый столбец, в каждой строке которого будет указан номер строки, ближайшей по евклидову расстоянию к данной строке.

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1), columns=list('pqrs'), index=list('abcdefghij'))
df
#     p   q   r   s
# a  57  77  13  62
# b  68   5  92  24
# c  74  40  18  37
# d  80  17  39  60
# e  93  48  85  33
# f  69  55   8  11
# g  39  23  88  53
# h  63  28  25  61
# i  18   4  73   7
# j  79  12  45  34
```

Пример выходных данных:

```python
df
#    p   q   r   s nearest_row   dist
# a  57  77  13  62           i  116.0
# b  68   5  92  24           a  114.0
# c  74  40  18  37           i   91.0
# d  80  17  39  60           i   89.0
# e  93  48  85  33           i   92.0
# f  69  55   8  11           g  100.0
# g  39  23  88  53           f  100.0
# h  63  28  25  61           i   88.0
# i  18   4  73   7           a  116.0
# j  79  12  45  34           a   81.0
```

In [37]:
from scipy.spatial.distance import cdist

df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1),
                  columns=list('pqrs'), index=list('abcdefghij'))

distanses = cdist(df,df, 'euclidean')
np.fill_diagonal(distanses,np.inf)
df['nearest_raw'] = df.index[distanses.argmin(axis=1)]
df['dist'] = distanses.min(axis=1)
df

p   q   r   s nearest_raw    dist
a  83  82   6  87           h 53.9815
b  66  76   4  14           h 45.0555
c   6   6  79  27           f 38.5876
d  98   1  87  10           j 51.8266
e  94   1  49  74           g 58.2495
f  35  20  63  41           i 32.8329
g  51  23  17  68           h 50.1697
h  85  51  16  44           b 45.0555
i  48  32  42  23           f 32.8329
j  66  32  92  36           f 44.3959

## Упражнение № 60

Вычислите максимально возможное абсолютное значение корреляции каждого столбца с другими столбцами в `df`.

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))
```

In [38]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1),
                  columns=list('pqrstuvwxy'), index=list('abcdefgh'))
corr = df.corr().abs().to_numpy()
np.fill_diagonal(corr, 0)

print(pd.DataFrame(corr).max().max())

0.8500874487691609


## Упражнение № 61

Вычислите минимум-максимум для каждой строки `df`.

```python
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
```

In [39]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

pd.DataFrame([(min(df[i]), max(df[i])) for i in range(len(df))])

0   1
0   2  89
1   7  66
2   7  98
3  22  92
4   6  99
5   8  99
6  29  75
7   9  98

## Упражнение № 62

Создайте новый столбец `penultimate`, который содержит второе по величине значение каждой строки `df`.

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
```


In [40]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
df['penultimate'] = df.apply(lambda x: x.nlargest(2).iloc[1],axis=1)
df

0   1   2   3   4  ...   6   7   8   9  penultimate
0  88  22  27  72  77  ...  41  97  56  86           88
1  63  94  28  81  95  ...  53  92  24  55           94
2  21  54  15  24  33  ...  92  70  16  38           70
3  96  18  47  10  30  ...  74  86  78  14           86
4  59  85   5  92  76  ...  41  86  99   4           92
5  21  82  33  76  87  ...  37  11  43  50           82
6  97  56  75  72  23  ...  59  43  98  62           97
7  12  50  47   4  30  ...  58  46  84  11           84

[8 rows x 11 columns]

## Упражнение № 63

1. Нормализуйте все столбцы `df`, вычитая среднее значение столбца и деля его на стандартное отклонение.
2. Произведите ранжирование всех столбцов `df` таким образом, чтобы минимальное значение в каждом столбце было равно 0, а максимальное — 1.

Не используйте внешние пакеты типа `sklearn`.

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
```

In [41]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

df_norm = (df - df.mean()) / df.std()
df_rank = (df - df.min()) / (df.max() - df.min())

print(df_norm)
print(df_rank)

        0       1       2       3       4       5       6       7       8  \
0 -1.1244  0.3668  0.5568  0.9141 -1.0926  0.8626 -0.7749  1.2812 -0.0971   
1 -0.5224  1.0572  0.9085 -0.4493  1.0621 -1.8377  1.4794 -0.9731 -0.0349   
2 -0.3099  0.1251 -1.0550  1.2860 -0.2795 -0.4375 -0.4126 -0.7026  1.2695   
3 -1.3015  0.3323 -1.0257 -0.6972 -0.9707 -0.7376  0.1107  0.8003 -0.1902   
4  0.5401 -1.0831 -1.4067  0.9451  1.0215 -0.1375 -1.6606 -0.4020  1.3316   
5  1.1067 -1.9461  0.5568  0.3254 -1.2146  0.2625  0.1510  1.2211  0.3378   
6  0.1505  0.6084  1.1430 -0.9141  0.5743  0.9626  1.1171 -1.2737 -1.4326   
7  1.4608  0.5394  0.3224 -1.4099  0.8995  1.0626 -0.0101  0.0488 -1.1841   

        9  
0 -1.2099  
1 -0.8514  
2 -0.2172  
3  1.0789  
4  0.8859  
5  1.1341  
6 -1.1823  
7  0.3619  
       0      1      2      3      4      5      6      7      8      9
0 0.0641 0.7701 0.7701 0.8621 0.0536 0.9310 0.2821 1.0000 0.4831 0.0000
1 0.2821 1.0000 0.9080 0.3563 1.0000 0.0000 1.0000 0.1

## Упражнение № 64

Вычислите корреляцию каждой строки `df` с последующей строкой.

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))
```

In [42]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

df.corrwith(df.shift(-1))

0    0.1169
1   -0.1619
2   -0.1061
3   -0.7082
4    0.2409
5   -0.1989
6   -0.0816
7   -0.0200
8    0.3789
9   -0.5456
dtype: float64

## Упражнение № 65

Замените все значения в обеих диагоналях `df` на 0.

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))
df
#     0   1   2   3   4   5   6   7   8   9
# 0  11  46  26  44  11  62  18  70  68  26
# 1  87  71  52  50  81  43  83  39   3  59
# 2  47  76  93  77  73   2   2  16  14  26
# 3  64  18  74  22  16  37  60   8  66  39
# 4  10  18  39  98  25   8  32   6   3  29
# 5  29  91  27  86  23  84  28  31  97  10
# 6  37  71  70  65   4  72  82  89  12  97
# 7  65  22  97  75  17  10  43  78  12  77
# 8  47  57  96  55  17  83  61  85  26  86
# 9  76  80  28  45  77  12  67  80   7  63
```

Пример выходных данных:

```python
#     0   1   2   3   4   5   6   7   8   9
# 0   0  46  26  44  11  62  18  70  68   0
# 1  87   0  52  50  81  43  83  39   0  59
# 2  47  76   0  77  73   2   2   0  14  26
# 3  64  18  74   0  16  37   0   8  66  39
# 4  10  18  39  98   0   0  32   6   3  29
# 5  29  91  27  86   0   0  28  31  97  10
# 6  37  71  70   0   4  72   0  89  12  97
# 7  65  22   0  75  17  10  43   0  12  77
# 8  47   0  96  55  17  83  61  85   0  86
# 9   0  80  28  45  77  12  67  80   7   0
```

In [43]:
df = pd.DataFrame(np.random.randint(1,100, 100).reshape(10, -1))
np.fill_diagonal(df.values, 0)
for i in range(df.shape[0]):
    df.iloc[i, df.shape[1] - i - 1] = 0

print(df)

    0   1   2   3   4   5   6   7   8   9
0   0  92  49  31  98  50  27  74  83   0
1  40   0  26  59  97   4  28  52   0  48
2  22  70   0  67  80  60  55   0  83  25
3  91   9  50   0  82  25   0  47  34   7
4  18  55  64   5   0   0  12  92  69  74
5  17  19  13  86   0   0  27  50  89  18
6  52  27  13   0  84  88   0  86  64  31
7  72  99   0  60  85  92  55   0  67  27
8   2   0  65  47  76  31  76  66   0  53
9   0  77  71  62  17  46  35   2  27   0


## Упражнение № 66

Из `df_grouped` получите в виде датафрейма группу, относящуюся к `apple`.

Пример входных данных:

```python
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                   'col2': np.random.rand(9),
                   'col3': np.random.randint(0, 15, 9)})

df_grouped = df.groupby(['col1'])
```

Пример выходных данных

```
    col1      col2  col3
0  apple  0.673434     7
3  apple  0.182348    14
6  apple  0.050457     3
```


In [47]:
df = pd.DataFrame({'col1': ['apple', 'banana', 'orange'] * 3,
                     'col2': np.random.rand(9),
                     'col3': np.random.randint(0, 15, 9)})
df_grouped = df.groupby('col1')
apple_group = df_grouped.get_group('apple')
print(apple_group)

    col1   col2  col3
0  apple 0.6177    14
3  apple 0.4452    13
6  apple 0.0640    12


## Упражнение № 67

В `df` найдите второе по величине значение `taste` для `banana`.

Пример входных данных:

```python
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})
```

In [48]:
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'taste': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

banana_df = df[df['fruit'] == 'banana']
top_2_banana = banana_df['taste'].nlargest(2).iloc[-1]
print(df)
print(top_2_banana)

    fruit  taste  price
0   apple 0.2990      0
1  banana 0.7280      6
2  orange 0.4765      1
3   apple 0.9826     14
4  banana 0.8147      9
5  orange 0.3621     14
6   apple 0.3050      7
7  banana 0.4623      8
8  orange 0.1259      6
0.727960770536167


## Упражнение № 68

В `df` вычислите среднюю цену `Price` каждого фрукта `Fruit`, сохраняя фрукт как еще один столбец вместо индекса.

Пример входных данных:

```python
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})
```

In [51]:
df = pd.DataFrame({
    'fruit': ['apple', 'banana', 'orange'] * 3,
    'rating': np.random.rand(9),
    'price': np.random.randint(0, 15, 9)
})

print("DF:")
print(df)
print("\n AVG:")
print(df.groupby('fruit', as_index=False)['price'].mean())

DF:
    fruit  rating  price
0   apple  0.7434      4
1  banana  0.4635      2
2  orange  0.7672      2
3   apple  0.9744     12
4  banana  0.8629      3
5  orange  0.4506      7
6   apple  0.8286      4
7  banana  0.7885      6
8  orange  0.7226      3

 AVG:
    fruit  price
0   apple 6.6667
1  banana 3.6667
2  orange 4.0000


## Упражнение № 69

Объединить датафреймы `df1` и `df2` по признакам `fruit-pazham` и `weight-kilo`.

Пример входных данных:

```python
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})
```


In [52]:
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

pd.merge(df1, df2, left_on=['fruit','weight'], right_on=['pazham','kilo'])

fruit weight  price_x  pazham  kilo  price_y
0   apple   high        9   apple  high        0
1  orange    low       14  orange   low       10
2   apple   high       14   apple  high        0
3  orange    low        9  orange   low       10
4   apple   high        3   apple  high        0
5  orange    low        3  orange   low       10

## Упражнение № 70

Создайте в `df` два новых столбца, один из них — `lag1` (сдвиг столбца `a` вниз на 1 строку) столбца 'a', а другой — `lead1` (сдвиг столбца `b` вверх на 1 строку).

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns = list('abcd'))

    a   b   c   d
0  66  34  76  47
1  20  86  10  81
2  75  73  51  28
3   1   1   9  83
4  30  47  67   4
```

Пример выходных данных:

```python
    a   b   c   d  a_lag1  b_lead1
0  66  34  76  47     NaN     86.0
1  20  86  10  81    66.0     73.0
2  75  73  51  28    20.0      1.0
3   1   1   9  83    75.0     47.0
4  30  47  67   4     1.0      NaN
```

In [53]:
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns =list('abcd'))

df['lag1'] = df['a'].shift(1)
df['lead1'] = df['b'].shift(-1)
df

a   b   c   d    lag1   lead1
0  40  80  94  72     NaN 56.0000
1  52  56  56  44 40.0000 30.0000
2  82  30  86  98 52.0000 16.0000
3  73  16  25  45 82.0000 98.0000
4  21  98  63  79 73.0000     NaN

## Упражнение № 71

Получите частоты уникальных значений по всему датафрейму `df`.

Пример входных данных:

```python
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns = list('abcd'))
```

In [55]:
df = pd.DataFrame(np.random.randint(1, 10, 20).reshape(-1, 4), columns=list('abcd'))

print("\n Freq DataFrame:")
print(df.stack().value_counts().sort_index())


 Freq DataFrame:
1    1
2    3
3    1
4    4
5    2
6    5
7    2
8    1
9    1
Name: count, dtype: int64


## Упражнение № 72

Разделите столбец `row` в `df` так, чтобы сформировать датафрейм с 3 столбцами, как показано в примере выходных данных. 

Пример входных данных:

```python
df = pd.DataFrame(["STD, City    State",
"33, Kolkata    West Bengal",
"44, Chennai    Tamil Nadu",
"40, Hyderabad    Telengana",
"80, Bangalore    Karnataka"], columns=['row'])

print(df)
#>                         row
#> 0          STD, City\tState
#> 1  33, Kolkata\tWest Bengal
#> 2   44, Chennai\tTamil Nadu
#> 3  40, Hyderabad\tTelengana
#> 4  80, Bangalore\tKarnataka
```

Пример выходных данных:

```
0 STD        City        State
1  33     Kolkata  West Bengal
2  44     Chennai   Tamil Nadu
3  40   Hyderabad    Telengana
4  80   Bangalore    Karnataka
```


In [56]:
df = pd.DataFrame(["STD, City\tState",
                    "33, Kolkata\tWest Bengal",
                    "44, Chennai\tTamil Nadu",
                    "40, Hyderabad\tTelengana",
                    "80, Bangalore\tKarnataka"], columns=['row'])

df_split = df.row.str.split(', |\t', expand=True)
df_columns = df_split.iloc[0]
df_split = df_split[1:]
df_split.columns = df_columns

df_split

0 STD       City        State
1  33    Kolkata  West Bengal
2  44    Chennai   Tamil Nadu
3  40  Hyderabad    Telengana
4  80  Bangalore    Karnataka